export const meta = {
  name: 'research-2026-10-october-insertions',
  description: 'Insert AGNTCon Tokyo and AI-Agents-in-Depth evidence into the four unpublished October articles (zh + en, paste regenerated), and refresh backlog.md and style_brief.md for the 2026-10 cycle — every insertion planned, adversarially verified against the slides/notes, then applied.',
  phases: [
    { title: 'Plan', detail: 'one planner per article proposes 2–4 insertions with exact anchors' },
    { title: 'Verify', detail: 'a skeptic checks each insertion against the source and the article' },
    { title: 'Apply', detail: 'edit article.md + article.en.md, add References, regenerate paste' },
    { title: 'Loop files', detail: 'backlog.md and style_brief.md for 2026-10, verified' },
  ],
}

const ROOT = args.root
const TODAY = args.today
const DIR = `${ROOT}/research/2026-10`
const PREV = `${ROOT}/research/2026-09`
const CONF = `${ROOT}/.context/research/2026-09-conf`
const RAW = `${ROOT}/.context/research/2026-10`
const ARTICLES = [
  { dir: '2026-10-green-overview', name: '總論' },
  { dir: '2026-10-green-testing', name: '測試篇' },
  { dir: '2026-10-green-review', name: 'Review 篇' },
  { dir: '2026-10-green-reliability', name: '可靠度篇' },
]

const CONTEXT = `
Today is ${TODAY}. Repo root ${ROOT}; use absolute paths. The author (@fantasybz, Kochi Chuang) writes long-form Traditional-Chinese (Taiwan usage; English technical terms kept; single "—" dash, never "——") Medium articles for Engineering VPs / Staff engineers, plus an English edition of each. The October 2026 series 綠燈不是驗收 (Green Is Not Done: testing / review / reliability of agent output) is written and scheduled on Medium (10/06–10/29) but NOT yet published: ${ARTICLES.map(a => `${ROOT}/${a.dir}/article.md (+ article.en.md)`).join(', ')}.
The author attended AGNTCon + MCPCon Japan (Tokyo, Sep 10–11) and read Bojie Li's *AI Agents in Depth* v2.0, and asked for that material to be inserted into these unpublished articles. Sources: ${DIR}/conference_digest.md (§4 is a table of insertion candidates per article; §3 mechanisms; §8 quotes), ${CONF}/notes_sep10.md and ${CONF}/notes_sep11.md (per-session notes with slide numbers / timestamps — the ground truth), ${CONF}/files_txt/ (converted decks), ${DIR}/book_ai_agent_book.md (book notes with chapter / § / EN page), ${DIR}/arxiv.md (2026-09-01→15 sweep).
HARD RULES. (a) These articles are the author's prose: an insertion ADDS a sentence or a short paragraph (≤ 120 CJK characters, or one table row) with a citation; it never rewords, cuts or restructures existing text, never changes a heading, a figure, a table's columns, a code block or the TL;DR. (b) Every inserted fact must be traceable to a slide number / timestamp / book § in the sources; label vendor-reported numbers as such; no invented numbers. (c) An insertion must add evidence the article does not already have (check the References list and the body); do not restate an arXiv finding with a conference anecdote. (d) Match the author's voice (read style: first-person opinionated, numbers with sources, English terms untranslated). (e) Each insertion needs a References entry in the article's existing format (org — [title](url); use the sched.co URL https://sched.co/<id> for a session, the slide PDF URL from ${CONF}/sessions.md when there is one, and https://github.com/bojieli/ai-agent-book or the chapter page https://bojieli.github.io/ai-agent-book/book-en/<chapterN>/ for the book) — unless the References already carry that source. (f) The English edition mirrors 1:1: the same insertion in English at the same place, same References entry (English title). (g) Never touch publish/ files directly — the paste is regenerated by a script.`

const INSERTIONS = {
  type: 'object', required: ['article', 'insertions'],
  properties: {
    article: { type: 'string' },
    insertions: { type: 'array', items: { type: 'object', required: ['section', 'anchor_zh', 'anchor_en', 'text_zh', 'text_en', 'source', 'why', 'reference_zh', 'reference_en'], properties: {
      section: { type: 'string', description: 'the exact ## heading it goes under' },
      anchor_zh: { type: 'string', description: 'an exact, verbatim sentence from article.md AFTER which the text is inserted (copy-paste, including punctuation)' },
      anchor_en: { type: 'string', description: 'the corresponding verbatim sentence from article.en.md' },
      position: { type: 'string', enum: ['after-paragraph', 'new-paragraph-after', 'table-row-after'], description: 'after-paragraph = append to the same paragraph; new-paragraph-after = own paragraph after the anchor paragraph; table-row-after = a new table row after the row containing the anchor' },
      text_zh: { type: 'string' }, text_en: { type: 'string' },
      source: { type: 'string', description: 'session id + slide / timestamp, or book chapter §' },
      why: { type: 'string' },
      reference_zh: { type: 'string', description: 'the References line in the article format, or "exists"' },
      reference_en: { type: 'string' },
    } } },
  },
}
const VERDICTS = {
  type: 'object', required: ['article', 'verdicts'],
  properties: {
    article: { type: 'string' },
    verdicts: { type: 'array', items: { type: 'object', required: ['index', 'keep', 'problems', 'text_zh', 'text_en'], properties: {
      index: { type: 'integer' }, keep: { type: 'boolean' },
      problems: { type: 'array', items: { type: 'string' } },
      text_zh: { type: 'string', description: 'the corrected zh text to use if keep (may equal the original)' },
      text_en: { type: 'string' },
      reference_zh: { type: 'string' }, reference_en: { type: 'string' },
    } } },
  },
}
const FILE = { type: 'object', required: ['path', 'summary', 'applied', 'skipped'], properties: { path: { type: 'string' }, summary: { type: 'string' }, applied: { type: 'number' }, skipped: { type: 'array', items: { type: 'string' } } } }
const ISSUES = { type: 'object', required: ['checked', 'issues', 'complete'], properties: { checked: { type: 'integer' }, complete: { type: 'boolean' }, issues: { type: 'array', items: { type: 'object', required: ['quote', 'problem', 'fix'], properties: { quote: { type: 'string' }, problem: { type: 'string' }, fix: { type: 'string' } } } } } }

// ---------------------------------------------------------------- Articles: plan → verify → apply (pipeline, no barrier)
log('Four article pipelines (plan → skeptic → apply) run alongside the backlog and style-brief refresh')
const articles = pipeline(ARTICLES,
  a => agent(`${CONTEXT}
TASK — Plan insertions for ${a.name} (${ROOT}/${a.dir}/article.md and article.en.md). Read both articles in full (note the References list and every source already cited), then ${DIR}/conference_digest.md §3, §4 (rows for this article), §8 and §10, then the sessions those rows cite in ${CONF}/notes_sep10.md / ${CONF}/notes_sep11.md (verify the slide / timestamp yourself), then ${DIR}/book_ai_agent_book.md (ch.1 §1.1.4 '給出了回答不等於完成了任務', §1.2 Verify / Correct, §1.3 提議者—審核者 and 邊界集 + 保留集, ch.5 coding agents, ch.7 evaluation, EXPERIMENT_CONVENTIONS.md's 'is not task-completion evidence', the honest negative results). Propose 2–4 insertions (at most one from the book per article unless a second is clearly stronger than any conference candidate), each placed where the article is already making the point the new evidence supports. anchor_zh / anchor_en must be verbatim sentences (grep them to be sure they occur exactly once). Write text_zh in the author's voice; text_en as the author's English edition would say it. Do not propose anything for the TL;DR, headings, figures, tables' structure, code blocks or the 結語's quotable line.`, { label: `plan:${a.name}`, phase: 'Plan', schema: INSERTIONS, effort: 'high' }),
  (p, a) => p && p.insertions.length ? agent(`${CONTEXT}
TASK — Skeptic for ${a.name}. For each proposed insertion below: (1) open the cited source (${CONF}/notes_sep10.md / notes_sep11.md, the deck in ${CONF}/files_txt/, or ${DIR}/book_ai_agent_book.md) and confirm every number, name and quote — try to refute; (2) grep ${ROOT}/${a.dir}/article.md for anchor_zh and article.en.md for anchor_en — each must occur exactly once; (3) confirm the article does not already carry the same evidence (grep the id / speaker / book chapter); (4) check the text obeys the hard rules (≤ 120 CJK chars, adds not rewords, voice, single "—", no "——", English terms kept, mainland terms absent); (5) check the References line format against the article's existing lines. keep=false if any of (1)–(3) fails; otherwise keep=true with the corrected text if you had to fix wording, a number or the reference line. Default to keep=false when uncertain.
PROPOSED:
${JSON.stringify(p, null, 1)}`, { label: `skeptic:${a.name}`, phase: 'Verify', schema: VERDICTS, effort: 'high' }).then(v => ({ plan: p, verdicts: v })) : null,
  (x, a) => {
    if (!x || !x.verdicts) return null
    const kept = x.verdicts.verdicts.filter(v => v.keep).map(v => ({ ...x.plan.insertions[v.index], text_zh: v.text_zh || x.plan.insertions[v.index].text_zh, text_en: v.text_en || x.plan.insertions[v.index].text_en, reference_zh: v.reference_zh || x.plan.insertions[v.index].reference_zh, reference_en: v.reference_en || x.plan.insertions[v.index].reference_en }))
    log(`${a.name}: ${x.plan.insertions.length} proposed, ${kept.length} kept`)
    if (!kept.length) return { article: a.dir, applied: 0, kept: [] }
    return agent(`${CONTEXT}
TASK — Apply ${kept.length} verified insertions to ${ROOT}/${a.dir}/article.md and article.en.md with the Edit tool. For each: locate anchor_zh (exactly once) and insert text_zh per 'position' (after-paragraph: same paragraph, one space or none as the surrounding CJK text does; new-paragraph-after: a blank line then the paragraph; table-row-after: a Markdown row after the anchor's row, same column count); same for anchor_en / text_en. Add the References lines (unless "exists") at the end of the numbered References list in each file, continuing the numbering, keeping the list's ordering convention. Then regenerate the paste for both languages exactly like this (no --tags: the existing headers carry the script's default tag line, so the default keeps them byte-identical) and paste the two commands' output in your summary:
  cd ${ROOT} && python3 research/scripts/article_to_paste.py ${a.dir} && python3 research/scripts/article_to_paste.py ${a.dir} --lang en
Then run: cd ${ROOT} && git diff --stat -- ${a.dir} and confirm that figures.json is unchanged (an insertion is prose only) and that publish/medium-paste.md and publish/en/medium-paste.md changed. Do NOT run the test suites (the main loop runs them once). Return path (the article dir), summary (with the commands' output), applied count, skipped with reasons.
INSERTIONS:
${JSON.stringify(kept, null, 1)}`, { label: `apply:${a.name}`, phase: 'Apply', schema: FILE, effort: 'medium' }).then(r => ({ article: a.dir, applied: r ? r.applied : null, kept, result: r }))
  }
)

// ---------------------------------------------------------------- Loop files (independent of the articles)
const loopFiles = parallel([
  async () => {
    const w = await agent(`${CONTEXT}
TASK — Write ${DIR}/backlog.md for the 2026-10 cycle. Read ${PREV}/backlog.md in full (its 使用規則, the nine numbered items with 升級條件 / 最早月份 / 上次評分, 插曲, 已被吸收的訊號, 訊號監看清單, 成效權重). Then read the 2026-10 digests: ${DIR}/x_digest.md, ${DIR}/community_digest.md, ${DIR}/arxiv.md, ${DIR}/notion_digest.md, ${DIR}/conference_digest.md (§9 backlog updates especially), ${DIR}/book_ai_agent_book.md (§1 and the chapter list). Produce the new backlog: same structure and rules, Traditional Chinese (Taiwan), single "—". For each of the nine items: update 上次評分 / evidence with what the fortnight added (cite digest section), move items up or down per the 升級條件, mark 「觀察中」 where nothing new arrived; add new items only when the conference or book gives a genuinely new theme (e.g. agent identity / delegated authorization; carbon-aware agents; agent memory as infrastructure; the 'Japan as a demand signal' cross-over) — each with 升級條件, 最早月份 and a first score; add the 'Tokyo field notes' 插曲 candidate from community_digest.md; update 已被吸收 for what the December re-cut now absorbs (read ${DIR}/selection.md if it exists, else ${DIR}/conference_digest.md §3); extend the 訊號監看清單 with the conference's accounts / projects / dates (Amsterdam Sep 17–18, NA Oct 22–23, Agent Router, agentgateway, AAIF WGs, the speakers worth following) and the new arXiv query strings; fill the 成效權重 table's 2026-09 row from community_digest.md's Medium section (views / reads / 完讀 for the September series, EN, fan-page share status) and state the delta since 2026-09-05. Names of private-group members stay out (role only), as the rules say. Return path and summary.`, { label: 'write:backlog', phase: 'Loop files', schema: FILE, effort: 'high' })
    if (!w) return null
    const v = await agent(`You are a skeptical fact-checker. Repo ${ROOT}. File: ${DIR}/backlog.md. Sources: ${PREV}/backlog.md, ${DIR}/x_digest.md, ${DIR}/community_digest.md, ${DIR}/arxiv.md, ${DIR}/notion_digest.md, ${DIR}/conference_digest.md, ${DIR}/book_ai_agent_book.md. Read the file end to end; confirm it ends cleanly and keeps every section of the 2026-09 backlog. Sample ≥ 25 concrete claims (numbers, reaction counts, arXiv ids, session ids, dates, names) and check each against the sources with grep; flag any private-group member named by name (the rule is role only). Report only issues you have the source line for.`, { label: 'verify:backlog', phase: 'Loop files', schema: ISSUES, effort: 'high' })
    if (v && (v.issues.length || !v.complete)) await agent(`Apply these corrections to ${DIR}/backlog.md with the Edit tool, nothing else; confirm the file ends cleanly.\n${JSON.stringify(v, null, 1)}`, { label: 'fix:backlog', phase: 'Loop files', effort: 'low' })
    return { file: 'backlog.md', checked: v ? v.checked : null, issues: v ? v.issues.length : null }
  },
  async () => {
    const w = await agent(`${CONTEXT}
TASK — Write ${DIR}/style_brief.md for the 2026-10 cycle. Start from ${PREV}/style_brief.md (copy its structure). Update: (1) the 'What the Medium data says about reception' section from ${DIR}/community_digest.md's Medium section (the September series' views / reads / 完讀 as of ${TODAY}, the lifetime leaders, the delta since 2026-09-05, the fan-page share status) — keep the correction note about Presentations / Views / Reads; (2) 'Series architecture' with the October series' real numbers (read the four articles' TL;DR shape and section counts: ${ARTICLES.map(a => `${ROOT}/${a.dir}/article.md`).join(', ')}; CJK counts: 總論 ≈ 10,000 / parts ≈ 7,600–7,800 — note that these exceed the 3,600 / 1,800–2,300 targets and that the author accepted it); (3) 'Rhetorical moves' — add what the October drafts and the voice polish of 2026-09-08 (see git log -5 --oneline and ${ROOT}/PUBLISHING.md〈目前的發布佇列〉) established: the 書錨 opening (Bach), Before/After config blocks, the 「設計規格，非現成工具」 label on YAML, the reader roles; (4) a new short section 'Conference and book material' — how the author cites a conference session (speaker, company, session, slide) and a book (《書名》第 N 章〈節〉), drawn from how the September articles cite Notion / workshop material; (5) 'Implications for the next themes' updated for the December re-cut (three artefacts, flight recorder / accountability) and the November backlog notes. Keep it under 9,000 characters, English as the original. Return path and summary.`, { label: 'write:style-brief', phase: 'Loop files', schema: FILE, effort: 'medium' })
    if (!w) return null
    const v = await agent(`You are a skeptical fact-checker. Repo ${ROOT}. File: ${DIR}/style_brief.md. Sources: ${PREV}/style_brief.md, ${DIR}/community_digest.md, the four October articles, ${ROOT}/PUBLISHING.md. Read the file; confirm every number (views, reads, percentages, character counts, dates) against the sources with grep or by counting (python3 -c "import re;print(len(re.findall(r'[\\u4e00-\\u9fff]', open('<path>').read())))"). Report only issues you have the source for.`, { label: 'verify:style-brief', phase: 'Loop files', schema: ISSUES, effort: 'medium' })
    if (v && (v.issues.length || !v.complete)) await agent(`Apply these corrections to ${DIR}/style_brief.md with the Edit tool, nothing else.\n${JSON.stringify(v, null, 1)}`, { label: 'fix:style-brief', phase: 'Loop files', effort: 'low' })
    return { file: 'style_brief.md', checked: v ? v.checked : null, issues: v ? v.issues.length : null }
  },
])

const [arts, loops] = await Promise.all([articles, loopFiles])
return { articles: arts.filter(Boolean).map(x => ({ article: x.article, applied: x.applied, kept: (x.kept || []).map(k => `${k.section} ← ${k.source}`) })), loopFiles: loops.filter(Boolean) }
